config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :withdrawals
  resources :deposites
  resources :users
  root 'static_page#home'

end

app/models/deposite.rb
class Deposite < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :deposites
         has_many :withdrawals
end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :add_parameter_to_user, if: :devise_controller?

  def add_parameter_to_user
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/deposites_controller.rb
class DepositesController < ApplicationController
  before_action :set_deposite, only: [:show, :edit, :update, :destroy]

  # GET /deposites
  # GET /deposites.json
  def index
    @deposites = Deposite.all
  end

  # GET /deposites/1
  # GET /deposites/1.json
  def show
  end

  # GET /deposites/new
  def new
    @deposite = current_user.deposites.build
  end

  # GET /deposites/1/edit
  def edit
  end

  # POST /deposites
  # POST /deposites.json
  def create
    @deposite = current_user.deposites.build(deposite_params)

    respond_to do |format|
      if @deposite.save
        format.html { redirect_to @deposite, notice: 'Deposite was successfully created.' }
        format.json { render :show, status: :created, location: @deposite }
      else
        format.html { render :new }
        format.json { render json: @deposite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposites/1
  # PATCH/PUT /deposites/1.json
  def update
    respond_to do |format|
      if @deposite.update(deposite_params)
        format.html { redirect_to @deposite, notice: 'Deposite was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposite }
      else
        format.html { render :edit }
        format.json { render json: @deposite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposites/1
  # DELETE /deposites/1.json
  def destroy
    @deposite.destroy
    respond_to do |format|
      format.html { redirect_to deposites_url, notice: 'Deposite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposite
      @deposite = Deposite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposite_params
      params.require(:deposite).permit(:date, :ammount)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

	def home
    

	end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController
  before_action :set_withdrawal, only: [:show, :edit, :update, :destroy]

  # GET /withdrawals
  # GET /withdrawals.json
  def index
    @withdrawals = Withdrawal.all
  end

  # GET /withdrawals/1
  # GET /withdrawals/1.json
  def show
  end

  # GET /withdrawals/new
  def new
    @withdrawal = current_user.withdrawals.build
  end

  # GET /withdrawals/1/edit
  def edit
  end

  # POST /withdrawals
  # POST /withdrawals.json
  def create
    @withdrawal = current_user.withdrawals.build(withdrawal_params)

    respond_to do |format|
      if @withdrawal.save
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully created.' }
        format.json { render :show, status: :created, location: @withdrawal }
      else
        format.html { render :new }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /withdrawals/1
  # PATCH/PUT /withdrawals/1.json
  def update
    respond_to do |format|
      if @withdrawal.update(withdrawal_params)
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully updated.' }
        format.json { render :show, status: :ok, location: @withdrawal }
      else
        format.html { render :edit }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /withdrawals/1
  # DELETE /withdrawals/1.json
  def destroy
    @withdrawal.destroy
    respond_to do |format|
      format.html { redirect_to withdrawals_url, notice: 'Withdrawal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdrawal
      @withdrawal = Withdrawal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdrawal_params
      params.require(:withdrawal).permit(:date, :ammount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposites_helper.rb
module DepositesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/deposites/_form.html.erb
<%= simple_form_for @deposite do |f| %>
  <% if @deposite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposite.errors.count, "error") %> prohibited this deposite from being saved:</h2>

      <ul>
      <% @deposite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input_field :date, class: "form-controle datepicker", as: :string %>
    <%= f.input :ammount %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposites/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Edit Deposite</h3>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>
<div class="panel-footer">
<%= link_to 'Show', @deposite, class: "btn btn-success" %>
<%= link_to "Back", deposites_path, class: "btn btn-warning" %>
</div>
</div>
</div>
</div>

app/views/deposites/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Listing Deposite</h3>
</div>
<div class="panel-body">
 <table class=" table table-hover table-bordered ">
  <thead>
    <tr>
      <th>Ammount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposites.each do |deposite| %>
      <tr>
        
        <td><%= deposite.ammount %></td>
        <td><%= deposite.date.strftime(" %m/%d/%Y") %></td>
        <td><%= link_to 'Show', deposite, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_deposite_path(deposite), class: "btn btn-warning" %></td>
       <td><%= link_to 'Destroy', deposite, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="panel-footer">
<%= link_to 'New Deposite', new_deposite_path , class: "btn btn-primary" %>
</div>
</div>
</div>
</div>

app/views/deposites/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">New Deposite</h3>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>
<div class="panel-footer">
<%= link_to "Back", deposites_path, class: "btn btn-warning" %>
</div>
</div>
</div>
</div>

app/views/deposites/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Listing Deposite</h3>
</div>
<div class="panel-body">
<p>
  <strong>Date:</strong>
  <%= @deposite.date.strftime( "%m/%d/%Y") %>
</p>

<p>
  <strong>Ammount:</strong>
  <%= @deposite.ammount %>
</p>
  </div>
  <div class="panel-footer">
  <%= link_to 'Edit', edit_deposite_path(@deposite), class: "btn btn-warning" %> |
<%= link_to 'Back', deposites_path, class: "btn btn-danger"%>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Banking</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
         <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Online Banking", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
           
           <% if user_signed_in? %>
           <li><%= link_to "Home", deposites_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          
            
            <% else %>
            

           <li><%= link_to "Create customer", new_user_registration_path %></li>
           <li><%= link_to "Log In", new_user_session_path %></li>
           <% end %>
          </ul>
    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/static_page/home.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="row">
      <div id="landing-content" class="col-lg-9">
        <h3><b>Welcome,</b></h3>
        <p>
          An Open Source Online Banking app using Ruby on Rails. This is not an exact copy of Banking S/W but has a similar functionality. This is to demonstrate how easy is it develop to a Online Banking app using Ruby on Rails.
        </p>
        <p>
        Deposite On Your Account
        </p>
        <p>
        <% if user_signed_in? %>
         <%= link_to "Start", new_deposite_path, class: "btn btn-success" %>
         <% end %>
        </p>
        </div>
        </div>
        </div>
        </div>
      
           

app/views/withdrawals/_form.html.erb
<%= simple_form_for @withdrawl do |f| %>
  <% if @withdrawl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@withdrawl.errors.count, "error") %> prohibited this withdrawl from being saved:</h2>

      <ul>
      <% @withdrawl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input_field :date, class: "form-controle datepicker", as: :string %>
    <%= f.input :ammount %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/withdrawals/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Edit Withdrawl</h3>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>
<div class="panel-footer">
<%= link_to 'Show', @withdrawal, class: "btn btn-success" %>
<%= link_to "Back", withdrawals_path, class: "btn btn-warning" %>
</div>
</div>
</div>
</div>

app/views/withdrawals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Listing Withdrawl</h3>
</div>
<div class="panel-body">
 <table class=" table table-hover table-bordered ">
  <thead>
    <tr>
      <th>Ammount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @withdrawals.each do |withdrawal| %>
      <tr>
        
        <td><%= withdrawal.ammount %></td>
        <td><%= withdrawal.date.strftime(" %m/%d/%Y") %></td>
        <td><%= link_to 'Show', withdrawal, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_withdrawal_path(withdrawal), class: "btn btn-warning" %></td>
       <td><%= link_to 'Destroy', withdrawal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="panel-footer">
<%= link_to 'New Withdrawal', new_withdrawal_path , class: "btn btn-primary" %>
</div>
</div>
</div>
</div>

app/views/withdrawals/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">New Withdrawl</h3>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>
<div class="panel-footer">
<%= link_to "Back", withdrawals_path, class: "btn btn-warning" %>
</div>
</div>
</div>
</div>

app/views/withdrawals/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Listing Withdrawl</h3>
</div>
<div class="panel-body">
<p>
  <strong>Ammount:</strong>
  <%= @withdrawal.ammount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @withdrawal.date.strftime( "%m/%d/%Y") %>
</p>
  </div>
  <div class="panel-footer">
  <%= link_to 'Edit', edit_withdrawal_path(@withdrawal), class: "btn btn-warning" %> |
<%= link_to 'Back', withdrawals_path, class: "btn btn-danger" %>
</div>
</div>
</div>
</div>